"""add column runtime

Revision ID: b036ad681384
Revises: d939f4425f42
Create Date: 2023-07-03 11:51:42.158420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b036ad681384'
down_revision = 'd939f4425f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runtime', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productions', schema=None) as batch_op:
        batch_op.drop_column('runtime')

    # ### end Alembic commands ###
